### PR TITLE
Disable logger

### PR DESCRIPTION
**Pull request by timsly**

### CODE REVIEW

**Comment by timsly** [comment]
Hi 
Yes, indeed, i disabled logger and there are two reasons for that:

1. I think this is how it should be, to my mind translation model shouldn't log to app logger by default
2. It was part of issues cleanup. There were few requests related to this feature

This and few other features will be part of 0.2.0 release. 
You can use 0.1.0 instead of master, because this is the latest stable release. And master may contain other non-compatible features in the future. So if you want to use master be ready for that

By the way, i disabled it only for `I18n::Backend::ActiveRecord::Translation` model are you saying that it had effect on other models?

**Comment by talakoski** [comment]
Hi,

I had the same problem. This nullified my `ActiveRecord::Base.logger` variable. I'm not sure why but seems that `logger` is a class variable and your code changes that even though you are doing it inside Translation class.

**Comment by timsly** [comment]
@talakoski ok, i will try to fix that. Just created an issue for that. See #75

**Comment by timsly** [comment]
Was my mistake there. I have reverted the code, so `logger` is no longer `nil`.

**Comment by talakoski** [comment]
Thanks! I think this was the fastest code fixing that I have ever experienced :)

**Pull request merged**
