### PR TITLE
Simplify generated migration

### PR DESCRIPTION
**Pull request by dorianmariefr**

### CODE REVIEW

**Comment by timfjord** [comment]
Great, thanks for the contribution @dorianmariefr

**Comment by dorianmariefr** [comment]
thanks for merging :) I think I may contribute a lot to this gem :)

**Comment by timfjord** [comment]
Awesome 👍🏻

**Comment by dorianmariefr** [comment]
How would you make it so that on translation missing it google translates
it and stores in the database ?

**Comment by timfjord** [comment]
I guess the only way to do this is to add Google API to your project and play around that

**Comment by dorianmariefr** [comment]
Yes that's what I did and I ended up with my own version of a solution without using your gem, but your gem gave me the great idea to store in active record the records. now I need to improve the performance etc. but it works https://socializus.app if you want to try

**Pull request merged**
